apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gravitee-apim.fullname" . }}-config
  labels:
    {{- include "gravitee-apim.labels" . | nindent 4 }}
data:
  # Repository types
  management-type: {{ .Values.management.type | quote }}
  ratelimit-type: {{ .Values.ratelimit.type | quote }}

  # JDBC
  jdbc-url: {{ .Values.jdbc.url | quote }}
  jdbc-schema: {{ .Values.jdbc.schema | quote }}
  jdbc-liquibase: {{ .Values.jdbc.liquibase | quote }}
  jdbc-driver-url: {{ .Values.jdbc.driver | quote }}
  jdbc-pool-auto-commit: {{ .Values.jdbc.pool.autoCommit | quote }}
  jdbc-pool-connection-timeout: {{ printf "%d" (int64 .Values.jdbc.pool.connectionTimeout) | quote }}
  jdbc-pool-idle-timeout: {{ printf "%d" (int64 .Values.jdbc.pool.idleTimeout) | quote }}
  jdbc-pool-max-lifetime: {{ printf "%d" (int64 .Values.jdbc.pool.maxLifetime) | quote }}
  jdbc-pool-min-idle: {{ printf "%d" (int64 .Values.jdbc.pool.minIdle) | quote }}
  jdbc-pool-max-pool-size: {{ printf "%d" (int64 .Values.jdbc.pool.maxPoolSize) | quote }}
  jdbc-pool-register-mbeans: {{ .Values.jdbc.pool.registerMbeans | quote }}

  # Redis
  {{- if .Values.redis.enabled }}
  redis-host: "{{ include "gravitee-apim.fullname" . }}-{{ .Values.redis.name }}"
  redis-port: {{ .Values.redis.service.port | quote }}
  {{- end }}

  # Elasticsearch
  {{- if .Values.es.enabled }}
  es-endpoint: {{ index .Values.es.endpoints 0 | quote }}
  es-security-enabled: {{ .Values.es.security.enabled | quote }}
  es-ssl-verify-hostname: {{ .Values.es.ssl.verifyHostname | quote }}
  es-ssl-trust-all: {{ .Values.es.ssl.trustAll | quote }}
  {{- end }}

  # Console UI
  console-management-api-url: {{ .Values.ui.managementApiUrl | quote }}

  # Portal UI
  portal-api-url: {{ .Values.portal.portalApiUrl | quote }}
