{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gravitee-apim.fullname" . }}-keycloak-data
  labels:
    {{- include "gravitee-apim.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.keycloak.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.keycloak.persistence.size }}
{{- end }}
