{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gravitee-apim.fullname" . }}-redis-data
  labels:
    {{- include "gravitee-apim.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.redis.name }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
