{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gravitee-apim.fullname" . }}-{{ .Values.redis.name }}
  labels:
    {{- include "gravitee-apim.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.redis.name }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ .Values.redis.name }}
    app.kubernetes.io/component: redis
{{- end }}
